### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by MisterDA**
Hi! This is a small PR to update Dune and Yojson to the latest versions, it also generates the opam file from the dune-project.

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
This is a great improvement, because I also just came here to this repository to suggest the migration from the `json` type to `t`. We plan to release Yojson 2.0 soon which after years of deprecation will finally remove the `json` type, so the more projects are upgraded to use the `t` type the fewer projects will break.

@Chris00 Could you take a look at this PR? Thanks in advance!

**Comment by Chris00** [comment]
I've applied the patch & a release [is pending](https://github.com/ocaml/opam-repository/pull/21440).

**Comment by Leonidas-from-XIV** [comment]
Excellent, thanks!

**Comment by Chris00** [comment]
Now merged.

**Pull request merged**
